### ISSUE TITLE
LocalBranchMissingException: local branch feature/Test does not exist

### ISSUE THREAD

**Issue by rohanmukesh** [RobWin/jgitflow-gradle-plugin#36]
When doing gradle featurePublish -PfeatureName="Test" I am getting this exception
Caused by: com.atlassian.jgitflow.core.exception.LocalBranchMissingException: local branch feature/Test does not exist
        at com.atlassian.jgitflow.core.util.RequirementHelper.requireLocalBranchExists(RequirementHelper.java:114)
        at com.atlassian.jgitflow.core.command.FeaturePublishCommand.call(FeaturePublishCommand.java:84)

Though I can see in my ref::
impl (feature/Test)
$ git show-ref
0a5d5b06077b50a53fd1e0187869866c2fb9dbcc refs/heads/Feature/Test

Also my plugin is applied at the root of the project.

**Comment by rohanmukesh** [comment]
Found out issue with name on our local refs/heads/**F**eature/Test. It should be small "f" and then it worked. Basically I had to go under .git/refs/head and change the Folder which had "Feature" to "feature"
